### ISSUE TITLE
Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#1]
```
mkdir hoodietest
cd hoodietest
npm init # accept all default values
npm install --save @hoodie/dev-top-level
```

Then added 

```json
"scripts": {
  "start": "hoodie"
},
"hoodie": {
  "plugins": [
    "hoodie-plugin-appconfig",
    "hoodie-plugin-email",
    "hoodie-plugin-users"
  ]
}
```

Now when running `npm start` I get 

```
$ npm start

> hoodietest@1.0.0 start /private/tmp/hoodietest
> hoodie


module.js:340
    throw err;
          ^
Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/private/tmp/hoodietest/node_modules/@hoodie/dev-top-level/node_modules/hoodie-server/lib/utils/index.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by gr2m** [comment]
oh, and `npm install mkdirp` fixes the problem

**Comment by boennemann** [comment]
@gr2m Confirmed. Seems like when exporting a binary from a dependency it could not be executed with the correct cmd or something like that. https://github.com/hoodiehq/hoodie/blob/master/package.json#L7

I'm looking into this now, but looking forward it would even make sense to rip that script out of hoodie-server and move it into this module directly.

**Comment by boennemann** [comment]
@gr2m After some investigation it appears that npm bundled an invalid cache from Travis. I've fixed that by disabling caching altogether. Given how sensible this step is it seems totally reasonable to do.

This fixed everything locally for me. Please confirm and close this issue then.

**Comment by gr2m** [comment]
confirmed :+1: it all works now
