### ISSUE TITLE
cannot not start CouchDB when the path contains a space

### ISSUE THREAD

**Issue by ssp** [hoodiehq/hoodie#324]
When hoodie is run in a location where any of the superfolders has a name including a space, it fails to start CouchDB (after 20 seconds of trying):

``` sh
➜  ~  mkdir "foo bar"
➜  ~  cd foo\ bar 
➜  foo bar  hoodie new test   

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.4.14 (node v0.10.28, npm 1.4.13, platform: darwin)

[hoodie] preparing test ...
[hoodie] Updated package.json
[hoodie] fetching npm dependencies
[hoodie] removing .git folder
[hoodie] created project at /Users/ssp/foo bar/test
[hoodie] Installed all dependencies

You can now start using your hoodie app

  cd test
  hoodie start

➜  foo bar  cd test
➜  test  hoodie start

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.4.14 (node v0.10.28, npm 1.4.13, platform: darwin)

Initializing...
CouchDB started: http://127.0.0.1:6012
Waiting for CouchDB [---*--] FAILED 

ERR! Error: Timed out waiting for CouchDB. These logs may help:
ERR!    /Users/ssp/foo bar/test/data/couch.stderr
ERR!    /Users/ssp/foo bar/test/data/couch.stdout
ERR!    /Users/ssp/foo bar/test/data/couch.log
ERR!     at Request._callback (/Users/ssp/foo bar/test/node_modules/hoodie-server/lib/couchdb/index.js:145:27)
ERR!     at self.callback (/Users/ssp/foo bar/test/node_modules/hoodie-server/node_modules/request/request.js:121:22)
ERR!     at Request.EventEmitter.emit (events.js:95:17)
ERR!     at ClientRequest.self.clientErrorHandler (/Users/ssp/foo bar/test/node_modules/hoodie-server/node_modules/request/request.js:230:10)
ERR!     at ClientRequest.EventEmitter.emit (events.js:95:17)
ERR!     at Socket.socketErrorListener (http.js:1547:9)
ERR!     at Socket.EventEmitter.emit (events.js:95:17)
ERR!     at net.js:440:14
ERR!     at process._tickDomainCallback (node.js:463:13)

Stopping CouchDB...
```

**Comment by gr2m** [comment]
@svnlto: could this be a hoodie-cli problem?

**Comment by svnlto** [comment]
@gr2m yeah, I think we're not resolving paths properly.

**Comment by gr2m** [comment]
moving to https://github.com/hoodiehq/hoodie-cli/issues/130
