### ISSUE TITLE
Unhandled rejection error (Promise) – follow up

### ISSUE THREAD

**Issue by mochtu** [hoodiehq/hoodie#418]
Follow up of #402
This happens continuously with hoodie.js v2.0.2 when server is offline/unreachable. I think it is directly related to hoodie requesting http://127.0.0.1:6005/_api/?hoodieId=…

```
Unhandled rejection Error: undefined
at Object.ensureErrorObject (http://127.0.0.1:6005/_api/_files/hoodie.js:5995:20)
at Promise.module.exports.Promise._rejectCallback (http://127.0.0.1:6005/_api/_files/hoodie.js:3906:22)
at http://127.0.0.1:6005/_api/_files/hoodie.js:3923:17
at Object.reject (http://127.0.0.1:6005/_api/_files/hoodie.js:11749:7)
at Object.reject (http://127.0.0.1:6005/_api/_files/hoodie.js:11858:12)
at exports.handleConnection (http://127.0.0.1:6005/_api/_files/hoodie.js:8053:48)
at ./promise (http://127.0.0.1:6005/_api/_files/hoodie.js:11812:33)
at tryCatcher (http://127.0.0.1:6005/_api/_files/hoodie.js:5793:31)
at Promise.module.exports.Promise._settlePromiseFromHandler (http://127.0.0.1:6005/_api/_files/hoodie.js:3944:31)
at Promise.module.exports.Promise._settlePromiseAt (http://127.0.0.1:6005/_api/_files/hoodie.js:4020:18)
at Promise.module.exports.Promise._settlePromises (http://127.0.0.1:6005/_api/_files/hoodie.js:4136:14)
at Async._drainQueue (http://127.0.0.1:6005/_api/_files/hoodie.js:1515:16)
at Async._drainQueues (http://127.0.0.1:6005/_api/_files/hoodie.js:1525:10)
at MutationObserver.drainQueues (http://127.0.0.1:6005/_api/_files/hoodie.js:1450:14) hoodie.js:2292
```

**Comment by gr2m** [comment]
Thanks @mochtu, I'll look into it!

**Comment by gr2m** [comment]
done: https://github.com/hoodiehq/hoodie.js/releases/tag/v2.0.3
