### ISSUE TITLE
Hoodie crashes on attempt to sync

### ISSUE THREAD

**Issue by jameswestnz** [hoodiehq/hoodie#549]
Had been testing a new version of `@hoodie/store-server` with @gr2m and run into an issue when replication/syncing kicks in on the client side. Error is as follows, with more info below:

```
_http_outgoing.js:392
    this._removedHeader[key] = true;
                             ^

TypeError: Cannot set property 'content-length' of undefined
    at ServerResponse.OutgoingMessage.removeHeader (_http_outgoing.js:392:30)
    at ServerResponse.onResponseHeaders (/Users/James/Documents/Projects/agtract/core/node_modules/compression/index.js:201:11)
    at ServerResponse.writeHead (/Users/James/Documents/Projects/agtract/core/node_modules/on-headers/index.js:46:16)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.write (/Users/James/Documents/Projects/agtract/core/node_modules/compression/index.js:83:14)
    at null._repeat (/Users/James/Documents/Projects/agtract/core/node_modules/express-pouchdb/lib/routes/changes.js:32:13)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

I hadn't seen this error prior to using testing these newer versions of `@hoodie/server` and `@hoodie/store-server`, so it is likely it can be resolved by going to back to stable versions. But apparently this has come up before. Can anyone shed any light here? I'm taking a look now.

**Comment by jameswestnz** [comment]
Related: https://github.com/expressjs/compression/issues/91

**Comment by jameswestnz** [comment]
The following raised this issue for me, and then was later resolved: https://github.com/hoodiehq/hoodie-server/pull/500

At present, safe to assume there was a bug in hoodie that is no longer present. Could you add your thoughts @gr2m?

**Comment by jameswestnz** [comment]
@imbolc, you may be interested?

**Comment by gr2m** [comment]
I’m quite certain that we resolved the issue as part of https://github.com/hoodiehq/hoodie-server/pull/500. Once we get https://github.com/hoodiehq/hoodie/pull/543 merged we should be all set, this is a non-breaking update

**Comment by gr2m** [comment]
I think we can close this now? I can’t reproduce it with the latest `hoodie` & `@hoodie/server`

**Comment by jameswestnz** [comment]
Agreed :)
