### ISSUE TITLE
PouchDB is undefined when using hoodie as hapi plugin

### ISSUE THREAD

**Issue by mammadzali** [hoodiehq/hoodie#734]
Got following error massage after trying this code: https://github.com/hoodiehq/hoodie#hapi-plugin

F:\hapi\hoodie-test-1\node_modules\@hoodie\server\lib\config\index.js:23
  var adapter = config.PouchDB.preferredAdapters[0] || 'http'
                              ^

TypeError: Cannot read property 'preferredAdapters' of undefined
    at getConfig (F:\hapi\hoodie-test-1\node_modules\@hoodie\server\lib\config\index.js:23:31)
    at Object.register (F:\hapi\hoodie-test-1\node_modules\@hoodie\server\index.js:12:3)
    at Object.target [as register] (F:\hapi\hoodie-test-1\node_modules\hapi\node_modules\joi\lib\object.js:77:34)
    at each (F:\hapi\hoodie-test-1\node_modules\hapi\lib\plugin.js:318:14)
    at iterate (F:\hapi\hoodie-test-1\node_modules\hapi\node_modules\items\lib\index.js:36:13)
    at Object.exports.serial (F:\hapi\hoodie-test-1\node_modules\hapi\node_modules\items\lib\index.js:39:9)
    at module.exports.internals.Plugin.internals.Plugin.register (F:\hapi\hoodie-test-1\node_modules\hapi\lib\plugin.js:321:11)
    at Object.register (F:\hapi\hoodie-test-1\node_modules\hoodie\server\index.js:22:10)
    at Object.target [as register] (F:\hapi\hoodie-test-1\node_modules\hapi\node_modules\joi\lib\object.js:77:34)
    at each (F:\hapi\hoodie-test-1\node_modules\hapi\lib\plugin.js:318:14)

**Comment by mammadzali** [comment]
SOLVED after:
1- "npm i -S pouchdb"
2- adding "var pouchDB = require('PouchDB')" to starting script (index.js)
3- make proper changes to options:
server.register({
  register: hoodie,
  options: { // pass options here
    PouchDB: pouchDB,
    inMemory: true,
    account: accountOptions
  }
...

and 
var accountOptions = {
  PouchDB: pouchDB,
  usersDb: 'my-users-db',
...

**Comment by gr2m** [comment]
Thanks for creating the issue and letting us know how you solved it! Could you please send a pull request which updates the code at https://github.com/hoodiehq/hoodie#hapi-plugin? The table below already states correctly that `options.PouchDB` is required, but it’s not yet reflected in the example code

**Comment by mammadzali** [comment]
Sure but the problem is I'm new in git and don't know how to do it

**Comment by gr2m** [comment]
no problem, I’m happy to walk you trough. [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal. Maybe watch that first and see how far you get? Let me know if you have any questions and I will help to fill in the gaps :)
