### ISSUE TITLE
npm5 support

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie#746]
To reproduce:

```
npm install -g npm5
> hoodie@0.0.0-semantically-released postinstall /Users/jan/Work/hoodie/hoodie
> node ./bin/setup.js
> npm5 install
[…]
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/jan/Work/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jan/Work/hoodie/hoodie/bin/setup.js:15:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hoodie@0.0.0-semantically-released postinstall: `node ./bin/setup.js`
[…]
```

**Comment by janl** [comment]
I’ve raised a question with npm about this: https://github.com/npm/npm/issues/16510#issuecomment-304255328
